### ISSUE TITLE
bug: can't implement approved suggestions

### ISSUE THREAD

**Issue by ironbelly** [yagpdb-cc/yagpdb-cc#75] opened 2020-09-05 04:23 UTC
No problems approving or implementing normal suggestions however when -sa implement is used on an approved task I get "Error: Not a valid Suggestion Message"

**Comment by TruRP** [comment] 2020-09-07 20:05
I get the same issue @Satty9361. I have tried all manor of passing an ID to the bot. This happens with or without a comment.

**Comment by Olde7325** [comment] 2021-01-01 23:47
Hey, sorry to necro this.

Can you tell me what message ID you provided as suggestion message?

**Comment by l-zeuch** [comment] 2021-04-18 19:06
@jo3-l what do you think about closing this due to inactivity?

**Comment by jo3-l** [comment] 2021-04-18 19:10
Is this bug reproducible on your end @l-zeuch?

**Comment by l-zeuch** [comment] 2021-04-18 19:15
Couldn't reproduce with several configurations... What about your end?

**Comment by jo3-l** [comment] 2021-04-18 19:17
Neither could I. Let's close this then. Feel free to open a new issue if it pops up with more information @ironbelly : )

**Closed by jo3-l** 2021-04-18 19:17 UTC
Labels: bug
